# Generated by Django 3.1.2 on 2020-10-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
