# Generated by Django 3.1.2 on 2020-11-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_user_re_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='estetician',
            field=models.CharField(choices=[('José Lopez', 'JL'), ('Mariela Hernández', 'MH')], max_length=25),
        ),
    ]
