# Generated by Django 3.1.2 on 2020-11-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20201114_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='estetician',
            field=models.CharField(choices=[('José López', 'José López'), ('Mariela Hernández', 'Mariela Hernández')], max_length=25),
        ),
    ]
