# Generated by Django 3.1.2 on 2020-11-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20201112_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='estetician',
            field=models.CharField(choices=[('José López', 'JL'), ('Mariela Hernández', 'MH')], max_length=25),
        ),
    ]
