# Generated by Django 3.1.2 on 2020-11-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20201109_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Massage', '0'), ('Manicure', '1'), ('Pedicure', '2'), ('Facial Cleansing', '3'), ('Permanent Hair Removal', '4'), ('Cryotherapy', '5')], max_length=25),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('8:00 AM', '8:00'), ('9:00 AM', '9:00'), ('10:00 AM', '10:00'), ('11:00 AM', '11:00'), ('1:00 PM', '13:00'), ('2:00 PM', '14:00'), ('3:00 PM', '15:00'), ('4:00 PM', '16:00')], max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=6),
        ),
    ]
