# Generated by Django 3.1.2 on 2020-11-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20201110_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.PositiveIntegerField(max_length=2),
        ),
    ]
