# Generated by Django 3.1.2 on 2020-11-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20201110_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
