# Generated by Django 3.1.2 on 2020-11-10 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20201110_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='appointments.client'),
            preserve_default=False,
        ),
    ]
